name: it-client
on:
  workflow_call:
env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
jobs:
  it-client:
    name: it-client
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: pipeline-safe-mode-test
      - name: Cache for maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-8-single
          restore-keys: |
            maven-repo-${{ hashFiles('**/pom.xml') }}-8
            maven-repo-${{ hashFiles('**/pom.xml') }}
            maven-repo-
      - name: Execute tests
        run: hadoop-ozone/dev-support/checks/integration.sh -Dtest=TestSCMSafeModeWithPipelineRules
        env:
          ITERATIONS: 100
      - name: Summary of failures
        run: cat target/integration/summary.txt
        if: always()
      - name: Archive build results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: it-client
          path: target/integration
      - name: Delete temporary build artifacts before caching
        run: |
          #Never cache local artifacts
          rm -rf ~/.m2/repository/org/apache/ozone/hdds*
          rm -rf ~/.m2/repository/org/apache/ozone/ozone*
        if: always()